name: Code coverage
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: make LLAMA_CODE_COVERAGE=1 all
      - name: Run tests
        run: |
            make test
            make coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov-report/coverage.info
