name: Python check requirements.txt

on:
  push:
    paths:
      - 'check-requirements.sh'
      - 'convert*.py'
      - 'requirements*.txt'
  pull_request:
    paths:
      - 'check-requirements.sh'
      - 'convert*.py'
      - 'requirements*.txt'

jobs:
  python-check-requirements:
    runs-on: ubuntu-latest
    name: check-requirements
    steps:
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install shellcheck
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run check-requirements.sh script
        run:  bash check-requirements.sh
