# Server test scenario
name: Server Integration Tests

# FIXME put only necessary triggers
on:
  push:
    branches:
      - master
      - test/server-add-ci-test # FIXME remove
    paths: ['.github/workflows/server-test.yml', '**/CMakeLists.txt', '**/*.h', '**/*.hpp', '**/*.c', '**/*.cpp', 'examples/server/**.*']

jobs:
  ubuntu-latest-cmake:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v3

      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install build-essential

      - name: Build
        id: cmake_build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release -j $(nproc)

      - name: Tests dependencies
        id: test_dependencies
        run: |
          pip install -r examples/server/tests/requirements.txt

      - name: Download test model
        id: download_model
        run: |
          ./scripts/hf.sh --repo ngxson/dummy-llama --file llama_xs_q4.bin

      - name: Server Integration Tests
        id: server_integration_test
        run: |
          cd examples/server/tests
          ./tests.sh ../../../llama_xs_q4.bin
          
          
